export { createLocation } from "./create"
export { getAllLocations } from "./getAllLocations"
export { getLocationById } from "./getLocationById"
export { deleteLocation } from "./remove"
export { updateLocation } from "./update"
