# Auto Label Git Action Config
# 'label_name'
#   - path_of_diff/where/code_lives/to_base_label_upon

Action:
  - .github/workflows/*

Config:
  - .github/config/*

App:
  - src/app/**/*

Util:
  - src/utils/**/*

