import type { Metadata } from "next"
import "./styles/globals.css"
import localFont from "next/font/local"
import { Suspense } from "react"
import { AuthInitializer } from "@/components/auth/AuthInitializer"
import { LogoutHandler } from "@/components/auth/LogoutHandler"

const BCSans = localFont({
  src: [
    {
      path: "../../public/fonts/BCSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/BCSans-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/BCSans-Bold.woff2",
      weight: "700",
      style: "bold",
    },
    {
      path: "../../public/fonts/BCSans-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-BCSans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${BCSans.variable} font-sans`}>
        <AuthInitializer />
        <Suspense fallback={null}>
          {/* Suspense is required because LogoutHandler uses useSearchParams */}
          <LogoutHandler />
        </Suspense>
        {children}
      </body>
    </html>
  )
}
