version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/citz-sbc-queue
    command: sleep infinity
    ports:
      - "3000:3000"
      - "3001:3001"
      - "51204:51204"  # Vitest UI
    environment:
      - NODE_ENV=development
    # Podman-specific configurations
    security_opt:
      - label=disable
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
