name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Create labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = ["Action", "Config", "App", "Util"];

          for (const label of labels) {
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label,
                color: '2c4677'
              });
            }
            catch (e) {
              if (e.status !== 422) throw e; // 422 means already exists
            }
          }

  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yaml

